---
title: "Exp#439_DataAnalysis"
author: "Mona Khorani"
date: "1/31/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(MetaboAnalystR)
library(qs)
```

```{r}
mSet<-InitDataObjects("conc", "stat", FALSE);
mSet<-Read.TextData(mSet,"140-NormtoTIA-Ready.csv","colu","disc")
mSet<-SanityCheckData(mSet);
mSet<-ReplaceMin(mSet);
mSet<-PreparePrenormData(mSet);
```

#Pareto Scaling 
```{r}
mSet<-Normalization(mSet, "NULL", "ParetoNorm", "S10T0", ratio=FALSE);
Dataset_Pareto_NTIA=mSet$dataSet
NormData_Pareto_TIA=Dataset_Pareto_NTIA$norm
write.csv(NormData_Pareto_TIA, "NormData_Pareto_TIA.csv")
mSet<-PlotNormSummary(mSet, "ParetoTIA_", format ="png", dpi=300, width=NA);
mSet<-PlotSampleNormSummary(mSet, "ParetoTIA_0_", format = "png", dpi=300, width=NA)

```

#Logtransformation
```{r}
mSet<-Normalization(mSet, "NULL","LogNorm", "NULL", ref=NULL, ratio=FALSE);
Dataset_Pareto_LogTra_NTIA=mSet$dataSet
NormData_Pareto_LogTra_TIA=Dataset_Pareto_LogTra_NTIA$norm
write.csv(NormData_Pareto_LogTra_TIA, "NormData_LogTra_TIA.csv")
mSet<-PlotNormSummary(mSet, "LogTIA-norm_0_", format ="png", dpi=300, width=NA);
mSet<-PlotSampleNormSummary(mSet, "LogTIA-snorm_0_", format = "png", dpi=300, width=NA)
```


#Pareto Scaling-Logtransformation
```{r}
mSet<-Normalization(mSet, "NULL","LogNorm", "ParetoNorm", ref=NULL, ratio=FALSE);
Dataset_Pareto_LogTra_NTIA=mSet$dataSet
NormData_Pareto_LogTra_TIA=Dataset_Pareto_LogTra_NTIA$norm
write.csv(NormData_Pareto_LogTra_TIA, "NormData_Pareto_LogTra_TIA.csv")
mSet<-PlotNormSummary(mSet, "Log-Pareto-norm_0_", format ="png", dpi=300, width=NA);
mSet<-PlotSampleNormSummary(mSet, "Log-Pareto-snorm_0_", format = "png", dpi=300, width=NA)
```


